repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets (system gitleaks)
        entry: gitleaks protect --verbose --redact --staged
        language: system
        pass_filenames: false
